### PR TITLE
chore: NativeScript 7

### PR DESCRIPTION
**Pull request by NathanWalker**

### CODE REVIEW

**Comment by andrewm-mitchells** [comment]
Can on of you guys @SBats @jeremypele @sitefinitysteve @codeback merge this PR into master so we can continue using it in NativeScript 7 please?

It's one of essential plugins for our app and we can't rollout updated version without it.

Thank you in advance!

**Comment by sitefinitysteve** [comment]
@andrewm-mitchells I don't appear to be authorized to merge

**Comment by jeremypele** [comment]
@andrewm-mitchells Done 👍

**Comment by andrewm-mitchells** [comment]
> @andrewm-mitchells I don't appear to be authorized to merge

Thanks a lot!

**Pull request merged**
